### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by alexjorgef** [ook/dht11-json#1]
I try to build WiringPi but i have this output

gcc -I/home/pi/workspace/scripts/gpio/WiringPi/wiringPi dht11.c -o dht11

```
/tmp/ccZnynbX.o: In function `read_dht11_dat':
dht11.c:(.text+0x9c): undefined reference to `delay'
dht11.c:(.text+0xb8): undefined reference to `delayMicroseconds'
dht11.c:(.text+0xf8): undefined reference to `delayMicroseconds'
dht11.c:(.text+0x280): undefined reference to `pinMode'
dht11.c:(.text+0x284): undefined reference to `digitalWrite'
dht11.c:(.text+0x288): undefined reference to `digitalRead'
/tmp/ccZnynbX.o: In function `main':
dht11.c:(.text+0x298): undefined reference to `wiringPiSetup'
dht11.c:(.text+0x2b8): undefined reference to `delay'
collect2: ld returned 1 exit status
```

(formatted by @ook)

**Comment by ook** [comment]
As say the compiler: wiringPi is missing. I doubt what you put in -l switch is the wiringPi module. I'm rather surprised that you don't give gcc your /usr/local/lib. If that can help you, here my build command line:

```
cc -o bin/dht11 dht11.c -L/usr/local/lib -lwiringPi
```

HTH.

**Comment by alexjorgef** [comment]
i'm a "noob atm with gcc package. thanks for the help ;) this build command fix my problem.
Alex

**Comment by ook** [comment]
Happy to know your problem is solved.
